[project]
name = "auth0blog-llamaindex"
version = "0.1.0"
description = ""
authors = [
    {name = "Raphael do Vale",email = "raphael@dovale.net"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "llama-index (>=0.12.0,<0.13.0)",
    "fastapi[standard] (>=0.115.0,<0.116.0)",
    "pydantic (>=2.11.7,<3.0.0)",
    "python-dotenv (>=1.1.1,<2.0.0)",
    "requests (>=2.32.5,<3.0.0)",
    "auth0-fastapi-api (>=1.0.0b3,<2.0.0)",
    "auth0-fastapi (>=1.0.0b4,<2.0.0)",
    "auth0-ai-llamaindex (>=0.2.0,<0.3.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
